name: Build develop aar

on:
  push:
    branches: [ develop ]
  pull_request:
    types: closed
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build usermanagerlib
      run: ./gradlew :usermanagerlib:assembleRelease
    
    - name: Upload usermanagerlib
      uses: actions/upload-artifact@v1.0.0
      with:
        name: usermanagerlib-release.aar
        path: ./usermanagerlib/build/outputs/aar
      
